export const FETCH_PROFILE = 'FETCH_PROFILE';
export const INIT_PROFILE = 'INIT_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const CLEAR_PROFILE_MESSAGE = 'CLEAR_PROFILE_MESSAGE';
